# Generated by Django 3.1.7 on 2021-03-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orikomi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=9, verbose_name='ジャンル')),
            ],
            options={
                'verbose_name_plural': 'genre',
            },
        ),
        migrations.AlterField(
            model_name='orikomi',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orikomi.genre', verbose_name='ジャンル'),
        ),
    ]
