# Generated by Django 3.1.7 on 2021-05-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orikomi', '0002_auto_20210328_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('drama', '演劇'), ('musical', 'ミュージカル'), ('live', 'ライブ'), ('dance', 'ダンス'), ('opera', 'オペラ'), ('concert', 'コンサート'), ('ballet', 'バレエ'), ('kabuki', '歌舞伎'), ('geino', '伝統芸能（能、狂言、文楽）'), ('rakugo', '落語'), ('other', 'その他')], max_length=9, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='orikomi',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='back_imeges/', verbose_name='チラシ裏面'),
        ),
        migrations.AlterField(
            model_name='orikomi',
            name='front_imege',
            field=models.ImageField(upload_to='front_imeges/', verbose_name='チラシ表面'),
        ),
    ]
